In [21]:
# This program predicts stock prices by using machine learning models
# -*- coding: utf-8 -*-
#Install the dependencies

import statistics as stat
import matplotlib as matlib
import bs4 as b4
import sklearn as sklrnb
import datetime as dt
import matplotlib.pyplot as plt
import pandas_datareader as pdr
import pandas_datareader.data as web
import os
import shutil
import bs4 as bs
import pickle
import requests

import pandas as pd
import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

import yfinance as yf

In [22]:
# Get the list of sp500 tickers
def save_sp500_tickers():
    try:
        f= open("sp500tickers.pickle","rb")
        print ('Using Pickle')
        tickers = pickle.loads(f.read())
        f.close()
    except IOError as err:
        resp = requests.get('http://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
        soup = bs.BeautifulSoup(resp.text, 'lxml')
        table = soup.find('table', {'class': 'wikitable sortable'})
        tickers = []
        for row in table.findAll('tr')[1:]:
            ticker = row.findAll('td')[0].text
            ticker = ticker.replace('\r', '')
            ticker = ticker.replace('\n', '')
            ticker = ticker.replace('.', '-')
            tickers.append(ticker)
        with open("sp500tickers.pickle","wb") as f:
            pickle.dump(tickers,f)  
    return tickers


In [23]:
tickers = save_sp500_tickers()

tickers_first = tickers[:150]
tickers_second = tickers[150:300]
tickers_third = tickers[300:]

# print(tickers)
# print(type(tickers))

Using Pickle


In [34]:
def get_predicted_price(ticker):
    try:
        # Get the Adjusted Close Price
        df = yf.Ticker(ticker).history(start='2014-12-3',end='2019-12-03').dropna()
        print(df.head())

        df = df[['Close']]
        #Take a look at the new data
        print(df.head())
        
        # A variable for predicting 'n' days out into the future
        forecast_out = 30 * 3 #'n=30' days
        #Create another column (the target or dependent variable) shifted 'n' units up
        df['Prediction'] = df[['Close']].shift(-forecast_out)
    
        #print the new data set
        print(df.tail())
    
        ### Create the independent data set (X)  #######
        # Convert the dataframe to a numpy array
        X = np.array(df.drop(['Prediction'],1))

        #Remove the last 'n' rows
        X = X[:-forecast_out]
        print(X)
        
        ### Create the dependent data set (y)  #####
        # Convert the dataframe to a numpy array (All of the values including the NaN's)
        y = np.array(df['Prediction'])
        # Get all of the y values except the last 'n' rows
        y = y[:-forecast_out]
        print(y)
    
        # Split the data into 80% training and 20% testing
        x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    
    #     # Create and train the Support Vector Machine (Regressor)
    #     svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1)
    #     svr_rbf.fit(x_train, y_train)
    
    #     # Testing Model: Score returns the coefficient of determination R^2 of the prediction. 
    #     # The best possible score is 1.0
    #     svm_confidence = svr_rbf.score(x_test, y_test)
    #     print("svm confidence: ", svm_confidence)
    
        # Create and train the Linear Regression  Model
        lr = LinearRegression()
        # Train the model
        lr.fit(x_train, y_train)
    
        # Testing Model: Score returns the coefficient of determination R^2 of the prediction. 
        # The best possible score is 1.0
        lr_confidence = lr.score(x_test, y_test)
        print("lr confidence: ", lr_confidence)
    
        # Set x_forecast equal to the last 30 rows of the original data set from Close column
        x_forecast = np.array(df.drop(['Prediction'],1))[-forecast_out:]
        print(x_forecast)
    
        # Print linear regression model predictions for the next 'n' days
        lr_prediction = lr.predict(x_forecast)
        print(lr_prediction)

    #     # Print support vector regressor model predictions for the next 'n' days
    #     svm_prediction = svr_rbf.predict(x_forecast)
    #     print(svm_prediction)
    except: 
        print(ticker + "has error!")
        continue
    
    return pd.DataFrame(lr_prediction)

SyntaxError: 'continue' not properly in loop (<ipython-input-34-b91c2d5ac1fd>, line 72)

In [37]:
appended_data=[]
for ticker in tickers_third:
    print (ticker)
    df = get_predicted_price(ticker)
    df['ticker'] = ticker
    appended_data.append (df)
    print (df.head())
   
alldf= pd.concat(appended_data)
txtName='sp500Prediction_P3.csv'

alldf.to_csv(txtName)
shutil.copy(txtName, os.path.join(os.environ["HOMEPATH"], "Desktop\stocks"))
print ('done')

LYB
             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  63.43  65.53  62.99  64.35  7430000        0.0             0
2014-12-04  63.97  66.33  63.93  66.33  7154100        0.0             0
2014-12-05  68.20  68.21  65.57  66.03  7066100        0.0             0
2014-12-08  65.55  66.03  62.34  63.52  7485800        0.0             0
2014-12-09  63.20  64.38  62.67  64.33  5000900        0.0             0
            Close
Date             
2014-12-03  64.35
2014-12-04  66.33
2014-12-05  66.03
2014-12-08  63.52
2014-12-09  64.33
            Close  Prediction
Date                         
2019-11-26  92.62         NaN
2019-11-27  93.50         NaN
2019-11-29  92.54         NaN
2019-12-02  92.65         NaN
2019-12-03  91.76         NaN
[[64.35]
 [66.33]
 [66.03]
 ...
 [84.24]
 [83.41]
 [83.25]]
[79.52 79.02 78.8  ... 92.54 92.65 91.76]
lr confidence:  0.3590436037337069
[[81.81]
 [8

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  49.05  49.39  48.61  49.32  2802000        0.0             0
2014-12-04  49.12  49.12  48.04  48.42  4674500        0.0             0
2014-12-05  48.31  48.72  47.96  48.30  3644400        0.0             0
2014-12-08  48.15  48.25  47.41  47.69  3551200        0.0             0
2014-12-09  46.93  47.57  46.65  47.54  4240600        0.0             0
            Close
Date             
2014-12-03  49.32
2014-12-04  48.42
2014-12-05  48.30
2014-12-08  47.69
2014-12-09  47.54
            Close  Prediction
Date                         
2019-11-26  15.00         NaN
2019-11-27  15.11         NaN
2019-11-29  14.95         NaN
2019-12-02  15.03         NaN
2019-12-03  14.51         NaN
[[49.32]
 [48.42]
 [48.3 ]
 ...
 [22.21]
 [21.75]
 [21.85]]
[53.15 52.96 52.   ... 14.95 15.03 14.51]
lr confidence:  0.5775806736219115
[[21.67]
 [21.52

             Open   High    Low  Close  Volume  Dividends  Stock Splits
Date                                                                   
2014-12-03  62.40  64.69  62.40  64.13  263900        0.0             0
2014-12-04  64.37  65.30  64.25  64.78  205600        0.0             0
2014-12-05  64.75  66.02  64.75  65.48  139000        0.0             0
2014-12-08  65.47  66.82  64.86  65.38  144300        0.0             0
2014-12-09  64.69  66.82  64.00  66.69  136600        0.0             0
            Close
Date             
2014-12-03  64.13
2014-12-04  64.78
2014-12-05  65.48
2014-12-08  65.38
2014-12-09  66.69
             Close  Prediction
Date                          
2019-11-26  401.90         NaN
2019-11-27  406.43         NaN
2019-11-29  403.82         NaN
2019-12-02  398.97         NaN
2019-12-03  397.67         NaN
[[ 64.13]
 [ 64.78]
 [ 65.48]
 ...
 [333.28]
 [343.  ]
 [346.93]]
[ 85.38  86.56  84.17 ... 403.82 398.97 397.67]
lr confidence:  0.8056861243659327
[[33

              Open    High     Low   Close  Volume  Dividends  Stock Splits
Date                                                                       
2014-12-03  112.98  116.55  112.98  114.63  914300        0.0             0
2014-12-04  114.53  115.64  113.93  114.31  434200        0.0             0
2014-12-05  113.97  114.78  112.37  112.76  503700        0.0             0
2014-12-08  112.18  112.56  108.05  108.74  983700        0.0             0
2014-12-09  108.39  109.71  107.55  109.68  701300        0.0             0
             Close
Date              
2014-12-03  114.63
2014-12-04  114.31
2014-12-05  112.76
2014-12-08  108.74
2014-12-09  109.68
             Close  Prediction
Date                          
2019-11-26  268.52         NaN
2019-11-27  271.34         NaN
2019-11-29  268.40         NaN
2019-12-02  268.01         NaN
2019-12-03  270.65         NaN
[[114.63]
 [114.31]
 [112.76]
 ...
 [225.8 ]
 [220.95]
 [222.88]]
[136.27 136.11 134.41 ... 268.4  268.01 270.65]
lr c

             Open   High    Low  Close  Volume  Dividends  Stock Splits
Date                                                                   
2014-12-03  67.08  67.08  66.34  66.65  482300        0.0             0
2014-12-04  66.71  66.96  66.14  66.39  376100        0.0             0
2014-12-05  66.43  66.83  66.19  66.65  383200        0.0             0
2014-12-08  66.78  67.06  66.24  66.59  435500        0.0             0
2014-12-09  66.22  66.73  65.93  66.57  494600        0.0             0
            Close
Date             
2014-12-03  66.65
2014-12-04  66.39
2014-12-05  66.65
2014-12-08  66.59
2014-12-09  66.57
             Close  Prediction
Date                          
2019-11-26  168.93         NaN
2019-11-27  169.43         NaN
2019-11-29  169.25         NaN
2019-12-02  169.21         NaN
2019-12-03  170.84         NaN
[[ 66.65]
 [ 66.39]
 [ 66.65]
 ...
 [158.29]
 [160.04]
 [162.02]]
[ 71.24  71.16  70.23 ... 169.25 169.21 170.84]
lr confidence:  0.87038905381779
[[161.

              Open    High     Low   Close   Volume  Dividends  Stock Splits
Date                                                                        
2014-12-03  201.83  203.08  201.04  202.68   711400        0.0             0
2014-12-04  202.90  203.88  201.15  202.99   597600        0.0             0
2014-12-05  203.16  204.02  202.11  203.76   557000        0.0             0
2014-12-08  203.85  205.43  202.65  203.91  1007400        0.0             0
2014-12-09  201.31  203.91  199.67  201.52  1645900        0.0             0
             Close
Date              
2014-12-03  202.68
2014-12-04  202.99
2014-12-05  203.76
2014-12-08  203.91
2014-12-09  201.52
             Close  Prediction
Date                          
2019-11-26  145.39         NaN
2019-11-27  145.88         NaN
2019-11-29  144.64         NaN
2019-12-02  143.51         NaN
2019-12-03  141.79         NaN
[[202.68]
 [202.99]
 [203.76]
 ...
 [139.56]
 [137.32]
 [138.15]]
[216.48 217.35 218.75 ... 144.64 143.51 141.7

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  41.18  41.44  41.00  41.32  4642200        0.0           0.0
2014-12-04  41.24  41.24  40.77  41.15  4743100        0.0           0.0
2014-12-05  41.44  42.52  41.42  42.03  9336200        0.0           0.0
2014-12-08  42.03  42.36  41.77  42.03  5475200        0.0           0.0
2014-12-09  41.59  41.97  41.13  41.92  5296800        0.0           0.0
            Close
Date             
2014-12-03  41.32
2014-12-04  41.15
2014-12-05  42.03
2014-12-08  42.03
2014-12-09  41.92
            Close  Prediction
Date                         
2019-11-26  49.77         NaN
2019-11-27  49.91         NaN
2019-11-29  49.91         NaN
2019-12-02  49.35         NaN
2019-12-03  48.35         NaN
[[41.32]
 [41.15]
 [42.03]
 ...
 [49.44]
 [49.21]
 [49.75]]
[38.23 38.34 37.97 ... 49.91 49.35 48.35]
lr confidence:  0.3636957086229723
[[49.07]
 [49.08

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  40.28  41.90  40.27  41.75  3194500        0.0             0
2014-12-04  41.78  41.78  41.08  41.24  1581300        0.0             0
2014-12-05  41.29  41.52  41.10  41.48  1214200        0.0             0
2014-12-08  41.40  41.51  40.35  40.59  1600000        0.0             0
2014-12-09  40.31  40.81  40.15  40.70  4878900        0.0             0
            Close
Date             
2014-12-03  41.75
2014-12-04  41.24
2014-12-05  41.48
2014-12-08  40.59
2014-12-09  40.70
            Close  Prediction
Date                         
2019-11-26  95.37         NaN
2019-11-27  95.60         NaN
2019-11-29  94.54         NaN
2019-12-02  94.21         NaN
2019-12-03  91.87         NaN
[[41.75]
 [41.24]
 [41.48]
 ...
 [99.04]
 [97.26]
 [97.32]]
[45.23 45.36 44.41 ... 94.54 94.21 91.87]
lr confidence:  0.7728822754117317
[[97.59]
 [96.21

             Open   High    Low  Close  Volume  Dividends  Stock Splits
Date                                                                   
2014-12-03  60.66  60.80  60.28  60.39  229600        0.0             0
2014-12-04  60.51  60.70  60.12  60.65  458800        0.0             0
2014-12-05  60.39  60.51  59.78  60.09  289100        0.0             0
2014-12-08  60.10  61.13  60.10  60.80  444600        0.0             0
2014-12-09  60.50  61.41  60.49  61.33  349800        0.0             0
            Close
Date             
2014-12-03  60.39
2014-12-04  60.65
2014-12-05  60.09
2014-12-08  60.80
2014-12-09  61.33
             Close  Prediction
Date                          
2019-11-26  137.07         NaN
2019-11-27  137.11         NaN
2019-11-29  136.11         NaN
2019-12-02  133.66         NaN
2019-12-03  134.12         NaN
[[ 60.39]
 [ 60.65]
 [ 60.09]
 ...
 [117.84]
 [117.78]
 [117.89]]
[ 63.44  63.99  63.84 ... 136.11 133.66 134.12]
lr confidence:  0.6843045664380213
[[11

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  35.32  35.46  34.71  35.19  9641400        0.0             0
2014-12-04  35.05  35.18  34.86  34.95  7161000        0.0             0
2014-12-05  35.07  35.12  34.79  35.03  7054100        0.0             0
2014-12-08  34.94  35.11  34.72  34.79  7372200        0.0             0
2014-12-09  34.63  35.20  34.48  35.09  6365200        0.0             0
            Close
Date             
2014-12-03  35.19
2014-12-04  34.95
2014-12-05  35.03
2014-12-08  34.79
2014-12-09  35.09
            Close  Prediction
Date                         
2019-11-26  52.62         NaN
2019-11-27  52.73         NaN
2019-11-29  52.54         NaN
2019-12-02  52.84         NaN
2019-12-03  53.13         NaN
[[35.19]
 [34.95]
 [35.03]
 ...
 [54.14]
 [54.13]
 [54.53]]
[34.45 34.23 33.92 ... 52.54 52.84 53.13]
lr confidence:  0.3751610209303252
[[54.58]
 [54.53

             Open   High    Low  Close    Volume  Dividends  Stock Splits
Date                                                                     
2014-12-03  32.00  32.76  31.98  32.73   9147400        0.0             0
2014-12-04  32.72  33.08  32.47  32.98   9165300        0.0             0
2014-12-05  33.15  33.83  33.13  33.38  11489700        0.0             0
2014-12-08  33.45  34.19  33.25  34.06  14069300        0.0             0
2014-12-09  33.63  34.19  33.39  34.15  12283800        0.0             0
            Close
Date             
2014-12-03  32.73
2014-12-04  32.98
2014-12-05  33.38
2014-12-08  34.06
2014-12-09  34.15
            Close  Prediction
Date                         
2019-11-26  49.41         NaN
2019-11-27  49.78         NaN
2019-11-29  49.48         NaN
2019-12-02  49.08         NaN
2019-12-03  48.11         NaN
[[32.73]
 [32.98]
 [33.38]
 ...
 [44.81]
 [44.19]
 [45.05]]
[33.61 33.58 33.03 ... 49.48 49.08 48.11]
lr confidence:  0.6353734630032752
[[44.54]


             Open   High    Low  Close  Volume  Dividends  Stock Splits
Date                                                                   
2014-12-03  45.00  45.17  44.88  45.06  418900        0.0             0
2014-12-04  44.94  45.22  44.56  45.04  727000        0.0             0
2014-12-05  45.15  45.15  44.58  44.83  475900        0.0             0
2014-12-08  44.73  45.36  44.73  45.19  945600        0.0             0
2014-12-09  44.72  45.21  44.38  45.06  526900        0.0             0
            Close
Date             
2014-12-03  45.06
2014-12-04  45.04
2014-12-05  44.83
2014-12-08  45.19
2014-12-09  45.06
             Close  Prediction
Date                          
2019-11-26  259.77         NaN
2019-11-27  258.18         NaN
2019-11-29  259.19         NaN
2019-12-02  256.57         NaN
2019-12-03  254.35         NaN
[[ 45.06]
 [ 45.04]
 [ 44.83]
 ...
 [230.9 ]
 [230.54]
 [235.89]]
[ 57.51  57.7   57.41 ... 259.19 256.57 254.35]
lr confidence:  0.8791038700503567
[[23

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  61.39  62.47  60.86  62.32  4356300       0.46             0
2014-12-04  61.59  62.63  60.24  62.11  6543800       0.00             0
2014-12-05  61.52  62.36  60.88  61.68  4511600       0.00             0
2014-12-08  60.85  60.86  58.68  58.81  7594700       0.00             0
2014-12-09  58.79  60.08  58.46  59.88  6015900       0.00             0
            Close
Date             
2014-12-03  62.32
2014-12-04  62.11
2014-12-05  61.68
2014-12-08  58.81
2014-12-09  59.88
            Close  Prediction
Date                         
2019-11-26  22.34         NaN
2019-11-27  22.73         NaN
2019-11-29  22.50         NaN
2019-12-02  23.00         NaN
2019-12-03  22.06         NaN
[[62.32]
 [62.11]
 [61.68]
 ...
 [21.94]
 [21.36]
 [21.63]]
[52.11 51.46 50.8  ... 22.5  23.   22.06]
lr confidence:  0.2934189609749749
[[20.59]
 [22.92

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  30.88  31.31  30.82  31.27  2698400        0.0             0
2014-12-04  31.18  31.21  31.00  31.15   912800        0.0             0
2014-12-05  31.21  31.55  31.06  31.52  1323300        0.0             0
2014-12-08  31.47  31.71  31.42  31.64  1916400        0.0             0
2014-12-09  31.22  31.33  30.83  31.28  2551100        0.0             0
            Close
Date             
2014-12-03  31.27
2014-12-04  31.15
2014-12-05  31.52
2014-12-08  31.64
2014-12-09  31.28
            Close  Prediction
Date                         
2019-11-26  18.83         NaN
2019-11-27  19.28         NaN
2019-11-29  19.22         NaN
2019-12-02  19.18         NaN
2019-12-03  18.63         NaN
[[31.27]
 [31.15]
 [31.52]
 ...
 [14.02]
 [13.76]
 [13.83]]
[34.27 33.99 33.47 ... 19.22 19.18 18.63]
lr confidence:  0.6988526139972462
[[13.8 ]
 [13.78

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  14.30  14.30  14.14  14.27  2691700        0.0             0
2014-12-04  14.18  14.28  14.12  14.18  1956000        0.0             0
2014-12-05  14.17  14.27  14.13  14.25  2038500        0.0             0
2014-12-08  14.24  14.30  13.99  14.02  1668800        0.0             0
2014-12-09  13.95  14.14  13.91  14.14  3162200        0.0             0
            Close
Date             
2014-12-03  14.27
2014-12-04  14.18
2014-12-05  14.25
2014-12-08  14.02
2014-12-09  14.14
            Close  Prediction
Date                         
2019-11-26  13.32         NaN
2019-11-27  13.38         NaN
2019-11-29  13.17         NaN
2019-12-02  13.17         NaN
2019-12-03  12.91         NaN
[[14.27]
 [14.18]
 [14.25]
 ...
 [13.74]
 [13.57]
 [13.61]]
[14.82 14.69 14.49 ... 13.17 13.17 12.91]
lr confidence:  0.11503848751850775
[[13.56]
 [13.5

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  45.59  45.79  45.29  45.74  3792000        0.0           0.0
2014-12-04  45.74  46.16  45.54  46.00  4128200        0.0           0.0
2014-12-05  46.10  46.21  45.90  46.13  3408200        0.0           0.0
2014-12-08  46.00  46.00  45.19  45.38  5155200        0.0           0.0
2014-12-09  45.08  45.23  44.57  45.06  5989000        0.0           0.0
            Close
Date             
2014-12-03  45.74
2014-12-04  46.00
2014-12-05  46.13
2014-12-08  45.38
2014-12-09  45.06
            Close  Prediction
Date                         
2019-11-26  93.09         NaN
2019-11-27  93.89         NaN
2019-11-29  93.49         NaN
2019-12-02  93.56         NaN
2019-12-03  92.46         NaN
[[45.74]
 [46.  ]
 [46.13]
 ...
 [86.25]
 [86.83]
 [87.09]]
[46.9  46.93 46.3  ... 93.49 93.56 92.46]
lr confidence:  0.7657037929992261
[[87.17]
 [86.75

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  60.55  61.14  60.25  60.99   814200        0.0             0
2014-12-04  60.62  60.77  60.17  60.49   924200        0.0             0
2014-12-05  60.59  60.69  60.17  60.37   676500        0.0             0
2014-12-08  60.07  60.36  59.37  59.59  1218700        0.0             0
2014-12-09  59.13  59.72  58.95  59.64  1264900        0.0             0
            Close
Date             
2014-12-03  60.99
2014-12-04  60.49
2014-12-05  60.37
2014-12-08  59.59
2014-12-09  59.64
            Close  Prediction
Date                         
2019-11-26  37.81         NaN
2019-11-27  38.32         NaN
2019-11-29  38.17         NaN
2019-12-02  37.54         NaN
2019-12-03  36.60         NaN
[[60.99]
 [60.49]
 [60.37]
 ...
 [29.35]
 [29.63]
 [29.82]]
[62.74 63.02 61.36 ... 38.17 37.54 36.6 ]
lr confidence:  0.2827145674950501
[[30.25]
 [30.  

              Open    High     Low   Close   Volume  Dividends  Stock Splits
Date                                                                        
2014-12-03  129.70  130.97  129.47  130.07  1166600        0.0             0
2014-12-04  129.71  130.49  128.35  129.03   949000        0.0             0
2014-12-05  132.18  137.27  131.97  136.27  2145700        0.0             0
2014-12-08  136.27  136.56  134.60  135.24  2355000        0.0             0
2014-12-09  133.93  136.62  133.26  136.15  1307800        0.0             0
             Close
Date              
2014-12-03  130.07
2014-12-04  129.03
2014-12-05  136.27
2014-12-08  135.24
2014-12-09  136.15
             Close  Prediction
Date                          
2019-11-26  352.53         NaN
2019-11-27  351.56         NaN
2019-11-29  351.77         NaN
2019-12-02  341.73         NaN
2019-12-03  343.15         NaN
[[130.07]
 [129.03]
 [136.27]
 ...
 [340.46]
 [352.13]
 [349.94]]
[151.25 151.38 148.4  ... 351.77 341.73 343.1

             Open   High    Low  Close    Volume  Dividends  Stock Splits
Date                                                                     
2014-12-03  28.82  28.82  26.90  27.50  11282300        0.0             0
2014-12-04  27.54  27.83  26.57  26.76   7394200        0.0             0
2014-12-05  26.65  26.82  26.26  26.51   4931400        0.0             0
2014-12-08  26.56  26.60  25.89  25.95   4665000        0.0             0
2014-12-09  26.08  26.32  25.85  26.11   5645700        0.0             0
            Close
Date             
2014-12-03  27.50
2014-12-04  26.76
2014-12-05  26.51
2014-12-08  25.95
2014-12-09  26.11
            Close  Prediction
Date                         
2019-11-26  38.92         NaN
2019-11-27  39.07         NaN
2019-11-29  39.73         NaN
2019-12-02  39.86         NaN
2019-12-03  40.41         NaN
[[27.5 ]
 [26.76]
 [26.51]
 ...
 [34.7 ]
 [34.81]
 [34.4 ]]
[23.73 23.68 23.55 ... 39.73 39.86 40.41]
lr confidence:  0.7578519251802992
[[34.43]


               Open     High      Low    Close  Volume  Dividends  \
Date                                                                
2014-12-03  1264.38  1273.49  1245.01  1255.86   36700          0   
2014-12-04  1250.90  1260.00  1238.13  1246.90   21900          0   
2014-12-05  1231.01  1255.85  1228.34  1252.87   32500          0   
2014-12-08  1257.55  1264.61  1246.20  1259.74   28400          0   
2014-12-09  1254.98  1263.80  1243.04  1254.00   19100          0   

            Stock Splits  
Date                      
2014-12-03             0  
2014-12-04             0  
2014-12-05             0  
2014-12-08             0  
2014-12-09             0  
              Close
Date               
2014-12-03  1255.86
2014-12-04  1246.90
2014-12-05  1252.87
2014-12-08  1259.74
2014-12-09  1254.00
              Close  Prediction
Date                           
2019-11-26  3806.99         NaN
2019-11-27  3803.18         NaN
2019-11-29  3791.89         NaN
2019-12-02  3758.00        

             Open   High    Low  Close    Volume  Dividends  Stock Splits
Date                                                                     
2014-12-03  78.37  79.19  78.36  78.81  296000.0        0.0             0
2014-12-04  78.55  79.37  78.48  79.30  380500.0        0.0             0
2014-12-05  79.43  79.83  78.52  78.93  419900.0        0.0             0
2014-12-08  78.48  79.35  77.48  77.76  448900.0        0.0             0
2014-12-09  76.85  76.87  75.44  76.82  722500.0        0.0             0
            Close
Date             
2014-12-03  78.81
2014-12-04  79.30
2014-12-05  78.93
2014-12-08  77.76
2014-12-09  76.82
             Close  Prediction
Date                          
2019-11-26  193.88         NaN
2019-11-27  195.41         NaN
2019-11-29  191.42         NaN
2019-12-02  186.11         NaN
2019-12-03  181.81         NaN
[[ 78.81]
 [ 79.3 ]
 [ 78.93]
 ...
 [163.71]
 [162.7 ]
 [164.52]]
[ 71.64  72.06  71.84 ... 191.42 186.11 181.81]
lr confidence:  0.8466277

             Open   High    Low  Close    Volume  Dividends  Stock Splits
Date                                                                     
2014-12-03  38.79  38.98  38.51  38.90  10326000        0.0             0
2014-12-04  38.96  38.96  38.38  38.75   9177100        0.0             0
2014-12-05  38.87  38.87  38.47  38.78   8925300        0.0             0
2014-12-08  38.76  38.87  38.23  38.26  12766500        0.0             0
2014-12-09  37.90  38.78  37.82  38.73  13897500        0.0             0
            Close
Date             
2014-12-03  38.90
2014-12-04  38.75
2014-12-05  38.78
2014-12-08  38.26
2014-12-09  38.73
            Close  Prediction
Date                         
2019-11-26  56.51         NaN
2019-11-27  56.61         NaN
2019-11-29  56.14         NaN
2019-12-02  55.43         NaN
2019-12-03  54.59         NaN
[[38.9 ]
 [38.75]
 [38.78]
 ...
 [57.85]
 [58.03]
 [58.24]]
[40.94 40.45 40.02 ... 56.14 55.43 54.59]
lr confidence:  0.7032141910814613
[[57.8 ]


              Open    High     Low   Close   Volume  Dividends  Stock Splits
Date                                                                        
2014-12-03  117.16  119.51  117.14  119.25   967300        0.0             0
2014-12-04  118.39  118.80  117.67  117.69  1194500        0.0             0
2014-12-05  117.80  118.72  117.42  117.85   971800        0.0             0
2014-12-08  117.80  118.41  115.29  115.82  1118600        0.0             0
2014-12-09  114.59  116.68  114.28  116.57   924300        0.0             0
             Close
Date              
2014-12-03  119.25
2014-12-04  117.69
2014-12-05  117.85
2014-12-08  115.82
2014-12-09  116.57
             Close  Prediction
Date                          
2019-11-26  200.38         NaN
2019-11-27  199.83         NaN
2019-11-29  198.79         NaN
2019-12-02  197.48         NaN
2019-12-03  196.15         NaN
[[119.25]
 [117.69]
 [117.85]
 ...
 [176.48]
 [175.53]
 [173.15]]
[112.59 112.43 110.74 ... 198.79 197.48 196.1

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  36.72  37.60  36.55  37.54  2130000        0.0           0.0
2014-12-04  37.57  37.63  37.23  37.41  1416000        0.0           0.0
2014-12-05  36.86  37.27  36.73  36.84  1614200        0.0           0.0
2014-12-08  36.83  36.83  35.70  35.80  1598400        0.0           0.0
2014-12-09  35.35  36.59  35.27  36.57  2089900        0.0           0.0
            Close
Date             
2014-12-03  37.54
2014-12-04  37.41
2014-12-05  36.84
2014-12-08  35.80
2014-12-09  36.57
            Close  Prediction
Date                         
2019-11-26  44.45         NaN
2019-11-27  44.34         NaN
2019-11-29  44.35         NaN
2019-12-02  43.79         NaN
2019-12-03  43.62         NaN
[[37.54]
 [37.41]
 [36.84]
 ...
 [39.09]
 [38.86]
 [39.02]]
[38.1  37.96 37.34 ... 44.35 43.79 43.62]
lr confidence:  0.2198756816763251
[[38.76]
 [38.75

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  43.95  44.24  43.75  43.80   568700        0.0             0
2014-12-04  43.75  43.94  43.37  43.51  1056900        0.0             0
2014-12-05  43.48  43.75  42.94  43.04   763200        0.0             0
2014-12-08  43.02  43.16  42.40  42.47   819700        0.0             0
2014-12-09  42.02  42.19  41.73  42.00  1096700        0.0             0
            Close
Date             
2014-12-03  43.80
2014-12-04  43.51
2014-12-05  43.04
2014-12-08  42.47
2014-12-09  42.00
            Close  Prediction
Date                         
2019-11-26  92.61         NaN
2019-11-27  93.53         NaN
2019-11-29  92.90         NaN
2019-12-02  92.15         NaN
2019-12-03  91.49         NaN
[[43.8 ]
 [43.51]
 [43.04]
 ...
 [94.98]
 [94.52]
 [94.95]]
[50.31 50.38 49.95 ... 92.9  92.15 91.49]
lr confidence:  0.8519138687272179
[[95.26]
 [87.45

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  67.91  68.33  67.62  68.30  3862000        0.0             0
2014-12-04  68.01  68.17  67.30  67.91  4111000        0.0             0
2014-12-05  68.01  68.05  67.57  67.90  4236600        0.0             0
2014-12-08  67.34  67.92  67.27  67.63  3270600        0.0             0
2014-12-09  67.06  67.47  66.43  67.45  3467800        0.0             0
            Close
Date             
2014-12-03  68.30
2014-12-04  67.91
2014-12-05  67.90
2014-12-08  67.63
2014-12-09  67.45
            Close  Prediction
Date                         
2019-11-26  82.27         NaN
2019-11-27  82.48         NaN
2019-11-29  82.93         NaN
2019-12-02  82.60         NaN
2019-12-03  82.97         NaN
[[68.3 ]
 [67.91]
 [67.9 ]
 ...
 [83.64]
 [84.24]
 [84.58]]
[62.41 67.86 68.1  ... 82.93 82.6  82.97]
lr confidence:  0.47413201176643294
[[85.35]
 [84.9

              Open    High     Low   Close   Volume  Dividends  Stock Splits
Date                                                                        
2014-12-03  146.03  152.42  145.81  149.37  2377000        0.0             0
2014-12-04  141.13  145.99  140.86  144.22  3434800        0.0             0
2014-12-05  143.83  145.67  141.51  141.71  3166300        0.0             0
2014-12-08  137.74  138.52  130.75  132.17  3663600        0.0             0
2014-12-09  131.93  136.34  131.81  135.10  2572400        0.0             0
             Close
Date              
2014-12-03  149.37
2014-12-04  144.22
2014-12-05  141.71
2014-12-08  132.17
2014-12-09  135.10
             Close  Prediction
Date                          
2019-11-26  127.68         NaN
2019-11-27  130.18         NaN
2019-11-29  127.84         NaN
2019-12-02  126.78         NaN
2019-12-03  123.49         NaN
[[149.37]
 [144.22]
 [141.71]
 ...
 [139.16]
 [135.44]
 [135.21]]
[178.36 178.65 176.37 ... 127.84 126.78 123.4

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  25.89  25.98  25.82  25.93  6258400     0.0000           0.0
2014-12-04  25.89  26.04  25.66  25.73  4341200     0.0000           0.0
2014-12-05  25.54  25.77  25.34  25.46  4385500     0.0000           0.0
2014-12-08  25.51  25.85  25.51  25.73  3908300     0.3725           0.0
2014-12-09  25.62  26.03  25.62  25.89  3898800     0.0000           0.0
            Close
Date             
2014-12-03  25.93
2014-12-04  25.73
2014-12-05  25.46
2014-12-08  25.73
2014-12-09  25.89
            Close  Prediction
Date                         
2019-11-26  33.69         NaN
2019-11-27  33.89         NaN
2019-11-29  33.62         NaN
2019-12-02  33.78         NaN
2019-12-03  33.78         NaN
[[25.93]
 [25.73]
 [25.46]
 ...
 [29.54]
 [29.4 ]
 [29.54]]
[24.81 24.74 24.61 ... 33.62 33.78 33.78]
lr confidence:  0.18297044904605364
[[29.29]
 [28.9

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  23.72  23.90  23.67  23.73  4923200        0.0             0
2014-12-04  23.74  23.84  23.65  23.74  3319500        0.0             0
2014-12-05  23.79  23.88  23.71  23.77  2888600        0.0             0
2014-12-08  23.81  23.96  23.74  23.79  4891000        0.0             0
2014-12-09  23.67  23.70  23.35  23.40  8200600        0.0             0
            Close
Date             
2014-12-03  23.73
2014-12-04  23.74
2014-12-05  23.77
2014-12-08  23.79
2014-12-09  23.40
            Close  Prediction
Date                         
2019-11-26  72.94         NaN
2019-11-27  73.14         NaN
2019-11-29  73.05         NaN
2019-12-02  71.65         NaN
2019-12-03  70.65         NaN
[[23.73]
 [23.74]
 [23.77]
 ...
 [80.91]
 [81.07]
 [81.59]]
[24.35 24.34 23.96 ... 73.05 71.65 70.65]
lr confidence:  0.926708128853312
[[81.09]
 [80.6 ]

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  34.23  34.36  33.64  34.04  6782900       0.00             0
2014-12-04  34.10  34.37  33.85  33.94  2853100       0.00             0
2014-12-05  33.64  34.08  33.56  33.86  4540100       0.00             0
2014-12-08  33.95  34.40  33.89  34.38  3399900       0.37             0
2014-12-09  34.17  34.61  34.12  34.60  2952300       0.00             0
            Close
Date             
2014-12-03  34.04
2014-12-04  33.94
2014-12-05  33.86
2014-12-08  34.38
2014-12-09  34.60
            Close  Prediction
Date                         
2019-11-26  59.05         NaN
2019-11-27  59.04         NaN
2019-11-29  58.83         NaN
2019-12-02  58.16         NaN
2019-12-03  58.02         NaN
[[34.04]
 [33.94]
 [33.86]
 ...
 [58.45]
 [58.71]
 [58.61]]
[34.77 34.82 34.54 ... 58.83 58.16 58.02]
lr confidence:  0.8651412872691824
[[58.38]
 [56.98

              Open    High     Low   Close   Volume  Dividends  Stock Splits
Date                                                                        
2014-12-03  121.02  123.51  120.71  123.51  1632700        0.0             0
2014-12-04  120.58  124.58  119.74  121.80  1989900        0.0             0
2014-12-05  121.63  122.71  120.63  121.89  1439600        0.0             0
2014-12-08  121.50  123.09  120.38  120.62  1042800        0.0             0
2014-12-09  118.84  122.44  118.29  121.52  1318300        0.0             0
             Close
Date              
2014-12-03  123.51
2014-12-04  121.80
2014-12-05  121.89
2014-12-08  120.62
2014-12-09  121.52
             Close  Prediction
Date                          
2019-11-26  100.05         NaN
2019-11-27   97.45         NaN
2019-11-29   96.96         NaN
2019-12-02   96.73         NaN
2019-12-03   94.07         NaN
[[123.51]
 [121.8 ]
 [121.89]
 ...
 [ 89.13]
 [ 89.3 ]
 [ 89.23]]
[108.17 106.9  103.03 ...  96.96  96.73  94.0

             Open   High    Low  Close    Volume  Dividends  Stock Splits
Date                                                                     
2014-12-03  61.52  62.53  61.36  62.14  13143700        0.0             0
2014-12-04  62.03  62.11  60.94  61.28   9374000        0.0             0
2014-12-05  61.00  61.75  61.00  61.30   6588600        0.0             0
2014-12-08  61.18  61.42  60.33  60.67   7201700        0.0             0
2014-12-09  60.12  61.17  60.04  61.00   7548400        0.0             0
            Close
Date             
2014-12-03  62.14
2014-12-04  61.28
2014-12-05  61.30
2014-12-08  60.67
2014-12-09  61.00
            Close  Prediction
Date                         
2019-11-26  83.98         NaN
2019-11-27  84.15         NaN
2019-11-29  82.91         NaN
2019-12-02  81.82         NaN
2019-12-03  79.96         NaN
[[62.14]
 [61.28]
 [61.3 ]
 ...
 [74.69]
 [74.18]
 [74.05]]
[57.53 57.07 56.4  ... 82.91 81.82 79.96]
lr confidence:  0.21004079526824782
[[73.81]

             Open   High    Low  Close  Volume  Dividends  Stock Splits
Date                                                                   
2014-12-03  52.44  52.92  52.34  52.83  622800        0.0             0
2014-12-04  52.78  53.10  52.42  52.90  411600        0.0             0
2014-12-05  53.34  54.02  53.17  53.54  607000        0.0             0
2014-12-08  53.48  54.17  53.12  53.83  526700        0.0             0
2014-12-09  52.97  53.94  52.74  53.71  524600        0.0             0
            Close
Date             
2014-12-03  52.83
2014-12-04  52.90
2014-12-05  53.54
2014-12-08  53.83
2014-12-09  53.71
            Close  Prediction
Date                         
2019-11-26  89.52         NaN
2019-11-27  90.48         NaN
2019-11-29  89.82         NaN
2019-12-02  88.26         NaN
2019-12-03  88.00         NaN
[[52.83]
 [52.9 ]
 [53.54]
 ...
 [86.25]
 [82.68]
 [84.49]]
[53.45 53.86 52.99 ... 89.82 88.26 88.  ]
lr confidence:  0.7092375218237217
[[81.53]
 [81.45]
 [80.

             Open   High    Low  Close  Volume  Dividends  Stock Splits
Date                                                                   
2014-12-03  52.66  52.93  52.48  52.87  430600        0.0             0
2014-12-04  53.49  53.50  52.91  53.22  615100        0.0             0
2014-12-05  53.00  53.32  52.59  53.31  668400        0.0             0
2014-12-08  53.34  53.98  53.34  53.47  985600        0.0             0
2014-12-09  53.26  54.00  53.23  53.71  801400        0.0             0
            Close
Date             
2014-12-03  52.87
2014-12-04  53.22
2014-12-05  53.31
2014-12-08  53.47
2014-12-09  53.71
            Close  Prediction
Date                         
2019-11-26  64.70         NaN
2019-11-27  65.07         NaN
2019-11-29  65.04         NaN
2019-12-02  63.77         NaN
2019-12-03  64.13         NaN
[[52.87]
 [53.22]
 [53.31]
 ...
 [64.98]
 [64.95]
 [65.02]]
[56.32 56.51 55.97 ... 65.04 63.77 64.13]
lr confidence:  0.16585851863933532
[[65.55]
 [65.74]
 [65

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  34.69  34.80  34.61  34.75  2198600        0.0             0
2014-12-04  34.79  34.90  34.68  34.79  1612600        0.0             0
2014-12-05  34.83  35.15  34.66  35.13  3726800        0.0             0
2014-12-08  35.18  35.22  34.78  34.87  1078800        0.0             0
2014-12-09  34.68  34.89  34.50  34.88  1263400        0.0             0
            Close
Date             
2014-12-03  34.75
2014-12-04  34.79
2014-12-05  35.13
2014-12-08  34.87
2014-12-09  34.88
            Close  Prediction
Date                         
2019-11-26  88.55         NaN
2019-11-27  88.62         NaN
2019-11-29  88.65         NaN
2019-12-02  87.69         NaN
2019-12-03  87.98         NaN
[[34.75]
 [34.79]
 [35.13]
 ...
 [86.29]
 [86.68]
 [89.87]]
[36.23 36.1  35.37 ... 88.65 87.69 87.98]
lr confidence:  0.9603614918608879
[[89.67]
 [89.04

              Open    High     Low   Close   Volume  Dividends  Stock Splits
Date                                                                        
2014-12-03  103.90  105.78  103.90  105.44  1384100        0.0             0
2014-12-04  105.20  105.52  103.62  103.98   985800        0.0             0
2014-12-05  102.40  103.33  101.51  102.18  1543600        0.0             0
2014-12-08  101.87  102.08   99.58   99.83  1076300        0.0             0
2014-12-09   98.18   99.39   97.62   99.29  1037100        0.0             0
             Close
Date              
2014-12-03  105.44
2014-12-04  103.98
2014-12-05  102.18
2014-12-08   99.83
2014-12-09   99.29
             Close  Prediction
Date                          
2019-11-26  196.32         NaN
2019-11-27  196.42         NaN
2019-11-29  195.84         NaN
2019-12-02  193.97         NaN
2019-12-03  194.04         NaN
[[105.44]
 [103.98]
 [102.18]
 ...
 [166.87]
 [165.23]
 [162.66]]
[102.62 102.8  100.98 ... 195.84 193.97 194.0

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  42.51  43.27  42.43  43.17  2332200        0.0           0.0
2014-12-04  43.12  43.44  42.99  43.26  2199000        0.0           0.0
2014-12-05  43.42  43.63  42.90  43.09  1912200        0.0           0.0
2014-12-08  42.95  43.38  42.85  42.96  1441600        0.1           0.0
2014-12-09  42.57  42.94  42.35  42.79  1943200        0.0           0.0
            Close
Date             
2014-12-03  43.17
2014-12-04  43.26
2014-12-05  43.09
2014-12-08  42.96
2014-12-09  42.79
             Close  Prediction
Date                          
2019-11-26  115.07         NaN
2019-11-27  116.07         NaN
2019-11-29  115.89         NaN
2019-12-02  115.74         NaN
2019-12-03  114.01         NaN
[[ 43.17]
 [ 43.26]
 [ 43.09]
 ...
 [105.46]
 [105.04]
 [106.34]]
[ 49.33  49.38  47.92 ... 115.89 115.74 114.01]
lr confidence:  0.83100996075115

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  59.42  59.58  58.54  58.88  3056600          0             0
2014-12-04  58.66  59.12  58.54  58.95  3087400          0             0
2014-12-05  58.98  59.14  58.56  58.85  2732000          0             0
2014-12-08  58.54  58.73  56.15  56.41  5057200          0             0
2014-12-09  55.04  56.20  53.44  56.14  6117600          0             0
            Close
Date             
2014-12-03  58.88
2014-12-04  58.95
2014-12-05  58.85
2014-12-08  56.41
2014-12-09  56.14
             Close  Prediction
Date                          
2019-11-26  162.54         NaN
2019-11-27  161.51         NaN
2019-11-29  162.89         NaN
2019-12-02  161.00         NaN
2019-12-03  161.57         NaN
[[ 58.88]
 [ 58.95]
 [ 58.85]
 ...
 [159.75]
 [159.35]
 [159.97]]
[ 67.21  67.91  65.81 ... 162.89 161.   161.57]
lr confidence:  0.87400964427772

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  50.63  50.87  49.58  50.36  4069100        0.0             0
2014-12-04  50.40  50.59  49.61  49.79  2161100        0.0             0
2014-12-05  50.13  50.17  49.34  50.02  2747600        0.0             0
2014-12-08  49.89  50.38  49.44  49.90  1825800        0.0             0
2014-12-09  49.13  49.89  48.67  49.54  3074000        0.0             0
            Close
Date             
2014-12-03  50.36
2014-12-04  49.79
2014-12-05  50.02
2014-12-08  49.90
2014-12-09  49.54
            Close  Prediction
Date                         
2019-11-26  59.26         NaN
2019-11-27  60.24         NaN
2019-11-29  59.68         NaN
2019-12-02  59.33         NaN
2019-12-03  58.21         NaN
[[50.36]
 [49.79]
 [50.02]
 ...
 [48.35]
 [47.51]
 [47.24]]
[43.08 42.54 43.66 ... 59.68 59.33 58.21]
lr confidence:  0.22959916307049463
[[46.91]
 [46.8

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  61.67  62.10  60.58  61.83  1117700          0             0
2014-12-04  61.40  62.68  61.15  62.50   887500          0             0
2014-12-05  62.66  62.81  61.98  62.63   767700          0             0
2014-12-08  61.99  63.24  61.32  61.69  1136400          0             0
2014-12-09  60.89  62.18  59.58  62.03   724900          0             0
            Close
Date             
2014-12-03  61.83
2014-12-04  62.50
2014-12-05  62.63
2014-12-08  61.69
2014-12-09  62.03
             Close  Prediction
Date                          
2019-11-26  278.86         NaN
2019-11-27  281.28         NaN
2019-11-29  283.04         NaN
2019-12-02  277.35         NaN
2019-12-03  279.01         NaN
[[ 61.83]
 [ 62.5 ]
 [ 62.63]
 ...
 [297.21]
 [285.73]
 [289.33]]
[ 80.75  82.84  73.29 ... 283.04 277.35 279.01]
lr confidence:  0.89095790167136

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  61.34  62.10  60.43  61.94  3870000        0.0             0
2014-12-04  63.18  65.16  62.45  64.80  6602900        0.0             0
2014-12-05  65.17  66.05  64.42  65.37  3988500        0.0             0
2014-12-08  65.04  65.91  63.31  64.24  3814900        0.0             0
2014-12-09  62.13  64.86  60.97  64.31  2993300        0.0             0
            Close
Date             
2014-12-03  61.94
2014-12-04  64.80
2014-12-05  65.37
2014-12-08  64.24
2014-12-09  64.31
            Close  Prediction
Date                         
2019-11-26  98.68         NaN
2019-11-27  99.18         NaN
2019-11-29  97.86         NaN
2019-12-02  98.36         NaN
2019-12-03  97.44         NaN
[[61.94]
 [64.8 ]
 [65.37]
 ...
 [85.45]
 [84.77]
 [85.08]]
[89.54 89.03 87.73 ... 97.86 98.36 97.44]
lr confidence:  0.16714622908711363
[[ 85.89]
 [ 86

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  37.55  37.61  37.28  37.42  4661000        0.0             0
2014-12-04  37.42  37.60  37.23  37.43  2910000        0.0             0
2014-12-05  37.06  37.26  36.89  37.14  4755900        0.0             0
2014-12-08  37.16  37.67  37.16  37.54  4903800        0.0             0
2014-12-09  37.62  37.78  37.35  37.61  3999600        0.0             0
            Close
Date             
2014-12-03  37.42
2014-12-04  37.43
2014-12-05  37.14
2014-12-08  37.54
2014-12-09  37.61
            Close  Prediction
Date                         
2019-11-26  62.25         NaN
2019-11-27  62.31         NaN
2019-11-29  61.99         NaN
2019-12-02  61.60         NaN
2019-12-03  62.37         NaN
[[37.42]
 [37.43]
 [37.14]
 ...
 [54.49]
 [54.22]
 [54.59]]
[35.31 35.24 35.24 ... 61.99 61.6  62.37]
lr confidence:  0.6601988489510505
[[54.95]
 [54.15

             Open   High    Low  Close    Volume  Dividends  Stock Splits
Date                                                                     
2014-12-03  36.84  36.99  36.68  36.86  11201400        0.0           0.0
2014-12-04  36.92  37.70  36.82  37.25  13999000        0.0           0.0
2014-12-05  37.79  38.44  37.76  38.28  14788200        0.0           0.0
2014-12-08  38.57  38.57  38.07  38.39  11770600        0.0           0.0
2014-12-09  38.05  38.15  37.65  38.03   8725600        0.0           0.0
            Close
Date             
2014-12-03  36.86
2014-12-04  37.25
2014-12-05  38.28
2014-12-08  38.39
2014-12-09  38.03
            Close  Prediction
Date                         
2019-11-26  84.56         NaN
2019-11-27  85.77         NaN
2019-11-29  85.43         NaN
2019-12-02  84.57         NaN
2019-12-03  84.82         NaN
[[36.86]
 [37.25]
 [38.28]
 ...
 [89.86]
 [90.19]
 [98.24]]
[44.26 44.37 43.79 ... 85.43 84.57 84.82]
lr confidence:  0.6251747941963054
[[97.16]


              Open    High     Low   Close  Volume  Dividends  Stock Splits
Date                                                                       
2014-12-03  103.93  106.36  103.93  106.23  255500          0             0
2014-12-04  105.83  106.95  105.57  106.75  320500          0             0
2014-12-05  107.37  111.49  107.00  110.58  580100          0             0
2014-12-08  110.45  112.53  110.03  110.28  332900          0             0
2014-12-09  111.24  114.10  109.77  113.74  731400          0             0
             Close
Date              
2014-12-03  106.23
2014-12-04  106.75
2014-12-05  110.58
2014-12-08  110.28
2014-12-09  113.74
             Close  Prediction
Date                          
2019-11-26  232.96         NaN
2019-11-27  234.87         NaN
2019-11-29  231.73         NaN
2019-12-02  229.79         NaN
2019-12-03  225.27         NaN
[[106.23]
 [106.75]
 [110.58]
 ...
 [226.07]
 [224.09]
 [233.79]]
[129.56 129.87 127.   ... 231.73 229.79 225.27]
lr c

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  34.92  35.00  34.78  34.94  2567300        0.0             0
2014-12-04  34.94  35.07  34.76  34.84  2522700        0.0             0
2014-12-05  34.91  34.97  34.72  34.92  1678600        0.0             0
2014-12-08  34.94  35.19  34.87  34.99  1877700        0.0             0
2014-12-09  34.77  34.97  34.46  34.95  2127000        0.0             0
            Close
Date             
2014-12-03  34.94
2014-12-04  34.84
2014-12-05  34.92
2014-12-08  34.99
2014-12-09  34.95
            Close  Prediction
Date                         
2019-11-26  80.65         NaN
2019-11-27  81.06         NaN
2019-11-29  80.55         NaN
2019-12-02  80.82         NaN
2019-12-03  81.30         NaN
[[34.94]
 [34.84]
 [34.92]
 ...
 [69.77]
 [69.78]
 [70.54]]
[33.44 33.14 33.15 ... 80.55 80.82 81.3 ]
lr confidence:  0.8854031179109542
[[69.6 ]
 [69.28

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  27.06  28.21  27.06  28.11  1186200          0             0
2014-12-04  27.91  28.21  27.50  27.94   952900          0             0
2014-12-05  27.95  28.26  27.61  27.81   714900          0             0
2014-12-08  27.75  27.75  26.10  26.56  2595400          0             0
2014-12-09  26.16  27.18  25.85  27.11  1355500          0             0
            Close
Date             
2014-12-03  28.11
2014-12-04  27.94
2014-12-05  27.81
2014-12-08  26.56
2014-12-09  27.11
             Close  Prediction
Date                          
2019-11-26  120.44         NaN
2019-11-27  121.58         NaN
2019-11-29  121.35         NaN
2019-12-02  120.73         NaN
2019-12-03  123.11         NaN
[[ 28.11]
 [ 27.94]
 [ 27.81]
 ...
 [118.9 ]
 [119.25]
 [121.78]]
[ 25.03  25.03  24.72 ... 121.35 120.73 123.11]
lr confidence:  0.83898774527326

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  57.55  58.22  57.49  58.14  1266300        0.0             0
2014-12-04  58.18  58.30  57.63  58.07   811200        0.0             0
2014-12-05  58.23  58.51  58.03  58.44   868800        0.0             0
2014-12-08  58.41  58.53  57.60  57.76   846200        0.0             0
2014-12-09  56.92  57.95  56.78  57.91  1426200        0.0             0
            Close
Date             
2014-12-03  58.14
2014-12-04  58.07
2014-12-05  58.44
2014-12-08  57.76
2014-12-09  57.91
            Close  Prediction
Date                         
2019-11-26  93.30         NaN
2019-11-27  93.41         NaN
2019-11-29  92.71         NaN
2019-12-02  90.96         NaN
2019-12-03  89.59         NaN
[[58.14]
 [58.07]
 [58.44]
 ...
 [90.46]
 [91.03]
 [92.71]]
[63.92 63.66 62.99 ... 92.71 90.96 89.59]
lr confidence:  0.6674424065318008
[[93.07]
 [92.41

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  48.15  48.87  47.88  48.82  5493600        0.0             0
2014-12-04  48.54  48.96  48.41  48.63  4114100        0.0             0
2014-12-05  48.84  48.90  48.48  48.78  3923500        0.0             0
2014-12-08  48.40  49.15  48.11  48.34  5914100        0.0             0
2014-12-09  47.87  48.63  47.67  48.28  8379200        0.0             0
            Close
Date             
2014-12-03  48.82
2014-12-04  48.63
2014-12-05  48.78
2014-12-08  48.34
2014-12-09  48.28
             Close  Prediction
Date                          
2019-11-26  119.13         NaN
2019-11-27  121.73         NaN
2019-11-29  120.21         NaN
2019-12-02  118.79         NaN
2019-12-03  117.75         NaN
[[ 48.82]
 [ 48.63]
 [ 48.78]
 ...
 [127.28]
 [125.65]
 [126.45]]
[ 51.67  51.59  50.63 ... 120.21 118.79 117.75]
lr confidence:  0.89727378161670

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  96.10  96.61  95.68  96.29  1502400        0.0             0
2014-12-04  96.01  96.85  95.83  96.42   838600        0.0             0
2014-12-05  96.36  96.55  95.54  96.53   634000        0.0             0
2014-12-08  96.47  96.75  95.16  95.49   772100        0.0             0
2014-12-09  94.50  95.45  93.16  95.41   816100        0.0             0
            Close
Date             
2014-12-03  96.29
2014-12-04  96.42
2014-12-05  96.53
2014-12-08  95.49
2014-12-09  95.41
             Close  Prediction
Date                          
2019-11-26  133.22         NaN
2019-11-27  133.52         NaN
2019-11-29  133.80         NaN
2019-12-02  133.55         NaN
2019-12-03  133.36         NaN
[[96.29]
 [96.42]
 [96.53]
 ...
 [93.84]
 [93.01]
 [92.69]]
[ 79.17  77.65  76.61 ... 133.8  133.55 133.36]
lr confidence:  0.2955538032860956
[[ 

              Open    High     Low   Close  Volume  Dividends  Stock Splits
Date                                                                       
2014-12-03  155.17  155.86  154.27  155.33  249500        0.0             0
2014-12-04  155.41  156.38  154.26  155.94  344300        0.0             0
2014-12-05  156.52  157.19  154.98  155.83  231400        0.0             0
2014-12-08  155.83  156.01  153.53  154.00  171600        0.0             0
2014-12-09  152.04  155.13  151.48  155.06  225600        0.0             0
             Close
Date              
2014-12-03  155.33
2014-12-04  155.94
2014-12-05  155.83
2014-12-08  154.00
2014-12-09  155.06
             Close  Prediction
Date                          
2019-11-26  573.44         NaN
2019-11-27  567.33         NaN
2019-11-29  567.10         NaN
2019-12-02  556.58         NaN
2019-12-03  555.51         NaN
[[155.33]
 [155.94]
 [155.83]
 ...
 [467.13]
 [470.72]
 [468.4 ]]
[176.78 176.59 174.44 ... 567.1  556.58 555.51]
lr c

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  32.16  32.68  32.07  32.65  3225500        0.0             0
2014-12-04  32.63  32.66  32.31  32.62  3322000        0.0             0
2014-12-05  32.78  33.49  32.78  33.36  4418500        0.0             0
2014-12-08  33.35  33.54  33.10  33.34  3453400        0.0             0
2014-12-09  33.02  33.52  32.89  33.48  5101900        0.0             0
            Close
Date             
2014-12-03  32.65
2014-12-04  32.62
2014-12-05  33.36
2014-12-08  33.34
2014-12-09  33.48
            Close  Prediction
Date                         
2019-11-26  54.43         NaN
2019-11-27  54.92         NaN
2019-11-29  54.72         NaN
2019-12-02  54.41         NaN
2019-12-03  53.21         NaN
[[32.65]
 [32.62]
 [33.36]
 ...
 [50.63]
 [50.34]
 [50.74]]
[34.01 33.92 33.34 ... 54.72 54.41 53.21]
lr confidence:  0.7055736422065426
[[50.29]
 [50.48

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  26.14  26.17  25.84  25.94  1373000        0.0             0
2014-12-04  25.94  26.02  25.79  25.97  1136500        0.0             0
2014-12-05  25.88  25.88  25.61  25.81   973800        0.0             0
2014-12-08  25.81  26.27  25.81  26.12  1214300        0.0             0
2014-12-09  26.03  26.41  25.98  26.25  1301600        0.0             0
            Close
Date             
2014-12-03  25.94
2014-12-04  25.97
2014-12-05  25.81
2014-12-08  26.12
2014-12-09  26.25
            Close  Prediction
Date                         
2019-11-26  47.96         NaN
2019-11-27  48.03         NaN
2019-11-29  48.05         NaN
2019-12-02  46.78         NaN
2019-12-03  47.12         NaN
[[25.94]
 [25.97]
 [25.81]
 ...
 [45.33]
 [45.59]
 [45.77]]
[27.77 27.97 27.96 ... 48.05 46.78 47.12]
lr confidence:  0.8605064305894916
[[46.23]
 [46.27

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  34.92  34.98  34.60  34.94  2916400          0           0.0
2014-12-04  34.82  35.33  34.62  34.79  2982400          0           0.0
2014-12-05  34.87  34.97  34.56  34.72  2244600          0           0.0
2014-12-08  34.69  35.13  34.03  34.31  2975000          0           0.0
2014-12-09  34.01  34.22  33.21  34.17  4963200          0           0.0
            Close
Date             
2014-12-03  34.94
2014-12-04  34.79
2014-12-05  34.72
2014-12-08  34.31
2014-12-09  34.17
            Close  Prediction
Date                         
2019-11-26  17.99         NaN
2019-11-27  19.10         NaN
2019-11-29  18.89         NaN
2019-12-02  18.44         NaN
2019-12-03  18.11         NaN
[[34.94]
 [34.79]
 [34.72]
 ...
 [27.34]
 [27.34]
 [27.24]]
[42.1  42.85 42.57 ... 18.89 18.44 18.11]
lr confidence:  0.6853619345049158
[[27.44]
 [24.08

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  59.53  60.21  57.89  59.29  4098400          0             0
2014-12-04  61.81  63.15  61.19  61.75  8908200          0             0
2014-12-05  62.58  64.98  61.95  63.03  8157000          0             0
2014-12-08  63.19  64.94  62.84  64.25  5467000          0             0
2014-12-09  61.64  63.34  61.11  62.52  9159900          0             0
            Close
Date             
2014-12-03  59.29
2014-12-04  61.75
2014-12-05  63.03
2014-12-08  64.25
2014-12-09  62.52
            Close  Prediction
Date                         
2019-11-26  92.76         NaN
2019-11-27  93.05         NaN
2019-11-29  92.80         NaN
2019-12-02  91.63         NaN
2019-12-03  88.87         NaN
[[59.29]
 [61.75]
 [63.03]
 ...
 [95.11]
 [93.93]
 [93.36]]
[60.99 62.2  61.49 ... 92.8  91.63 88.87]
lr confidence:  0.374815410910807
[[93.44]
 [93.93]

              Open    High     Low   Close   Volume  Dividends  Stock Splits
Date                                                                        
2014-12-03  109.57  113.21  108.91  112.51  1803300          0             0
2014-12-04  112.22  113.53  110.72  113.35  1537900          0             0
2014-12-05  115.17  116.29  112.96  114.54  1465800          0             0
2014-12-08  113.99  114.23  109.35  110.84  1490700          0             0
2014-12-09  108.91  109.38  106.37  109.31  2397400          0             0
             Close
Date              
2014-12-03  112.51
2014-12-04  113.35
2014-12-05  114.54
2014-12-08  110.84
2014-12-09  109.31
             Close  Prediction
Date                          
2019-11-26  156.29         NaN
2019-11-27  156.46         NaN
2019-11-29  153.05         NaN
2019-12-02  152.19         NaN
2019-12-03  149.37         NaN
[[112.51]
 [113.35]
 [114.54]
 ...
 [126.63]
 [127.74]
 [127.61]]
[ 99.3   97.49  96.46 ... 153.05 152.19 149.3

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  29.61  29.86  28.96  29.42  3947500        0.0             0
2014-12-04  29.37  29.69  29.10  29.21  2106400        0.0             0
2014-12-05  29.45  30.13  29.45  29.88  3097600        0.0             0
2014-12-08  29.82  30.38  29.75  30.01  2239900        0.0             0
2014-12-09  29.57  30.04  29.47  29.99  2647800        0.0             0
            Close
Date             
2014-12-03  29.42
2014-12-04  29.21
2014-12-05  29.88
2014-12-08  30.01
2014-12-09  29.99
            Close  Prediction
Date                         
2019-11-26  30.14         NaN
2019-11-27  30.65         NaN
2019-11-29  30.74         NaN
2019-12-02  30.48         NaN
2019-12-03  28.94         NaN
[[29.42]
 [29.21]
 [29.88]
 ...
 [32.52]
 [32.2 ]
 [32.65]]
[30.48 30.37 29.88 ... 30.74 30.48 28.94]
lr confidence:  0.3941891673137179
[[32.18]
 [32.47

             Open   High    Low  Close  Volume  Dividends  Stock Splits
Date                                                                   
2014-12-03  76.76  77.18  76.33  76.89  709600        0.0           0.0
2014-12-04  76.96  77.17  76.37  76.59  571100        0.0           0.0
2014-12-05  76.60  77.06  76.21  76.58  515600        0.0           0.0
2014-12-08  76.72  77.45  76.47  77.40  595000        0.0           0.0
2014-12-09  76.79  77.98  76.56  77.91  596300        0.0           0.0
            Close
Date             
2014-12-03  76.89
2014-12-04  76.59
2014-12-05  76.58
2014-12-08  77.40
2014-12-09  77.91
             Close  Prediction
Date                          
2019-11-26  133.28         NaN
2019-11-27  133.55         NaN
2019-11-29  133.73         NaN
2019-12-02  134.53         NaN
2019-12-03  135.37         NaN
[[ 76.89]
 [ 76.59]
 [ 76.58]
 ...
 [133.81]
 [121.09]
 [120.76]]
[ 82.94  83.38  82.24 ... 133.73 134.53 135.37]
lr confidence:  0.7367962795632523
[[11

             Open   High    Low  Close  Volume  Dividends  Stock Splits
Date                                                                   
2014-12-03  62.03  62.46  61.72  62.22  373200        0.0             0
2014-12-04  62.05  62.23  61.66  61.99  349000        0.0             0
2014-12-05  62.07  62.84  61.89  62.82  735300        0.0             0
2014-12-08  61.72  63.14  61.72  62.96  405600        0.0             0
2014-12-09  62.69  62.92  61.41  62.86  636500        0.0             0
            Close
Date             
2014-12-03  62.22
2014-12-04  61.99
2014-12-05  62.82
2014-12-08  62.96
2014-12-09  62.86
             Close  Prediction
Date                          
2019-11-26  147.53         NaN
2019-11-27  148.26         NaN
2019-11-29  147.23         NaN
2019-12-02  145.86         NaN
2019-12-03  144.72         NaN
[[ 62.22]
 [ 61.99]
 [ 62.82]
 ...
 [150.27]
 [149.72]
 [152.  ]]
[ 72.15  72.16  71.34 ... 147.23 145.86 144.72]
lr confidence:  0.8943499943192067
[[15

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  54.33  55.49  53.98  55.23  6460500          0             0
2014-12-04  54.92  55.02  54.45  54.85  4472300          0             0
2014-12-05  54.83  56.10  54.63  55.09  9210800          0             0
2014-12-08  54.80  55.00  53.56  53.61  6148600          0             0
2014-12-09  52.53  52.97  51.40  52.48  9618100          0             0
            Close
Date             
2014-12-03  55.23
2014-12-04  54.85
2014-12-05  55.09
2014-12-08  53.61
2014-12-09  52.48
            Close  Prediction
Date                         
2019-11-26  40.51         NaN
2019-11-27  40.40         NaN
2019-11-29  40.38         NaN
2019-12-02  39.86         NaN
2019-12-03  39.34         NaN
[[55.23]
 [54.85]
 [55.09]
 ...
 [51.05]
 [51.38]
 [51.85]]
[61.66 61.78 60.68 ... 40.38 39.86 39.34]
lr confidence:  0.17160176924686843
[[52.15]
 [52.5

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  63.04  64.47  62.88  64.43  1175400        0.0             0
2014-12-04  64.19  65.04  63.98  64.76  1063600        0.0             0
2014-12-05  64.57  64.83  63.85  64.04   693900        0.0             0
2014-12-08  63.75  63.85  62.43  62.68   619400        0.0             0
2014-12-09  62.00  63.45  61.86  63.43   723400        0.0             0
            Close
Date             
2014-12-03  64.43
2014-12-04  64.76
2014-12-05  64.04
2014-12-08  62.68
2014-12-09  63.43
             Close  Prediction
Date                          
2019-11-26  142.02         NaN
2019-11-27  143.76         NaN
2019-11-29  141.87         NaN
2019-12-02  141.58         NaN
2019-12-03  141.97         NaN
[[ 64.43]
 [ 64.76]
 [ 64.04]
 ...
 [136.94]
 [133.91]
 [136.2 ]]
[ 80.71  79.69  78.9  ... 141.87 141.58 141.97]
lr confidence:  0.46466825996454

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  75.84  75.89  74.72  74.95  6374300       0.48             0
2014-12-04  74.24  74.85  73.81  74.79  6901400       0.00             0
2014-12-05  74.84  74.85  73.69  74.23  6570100       0.00             0
2014-12-08  74.26  74.71  73.99  74.33  6266000       0.00             0
2014-12-09  73.81  74.31  72.93  73.74  6633600       0.00             0
            Close
Date             
2014-12-03  74.95
2014-12-04  74.79
2014-12-05  74.23
2014-12-08  74.33
2014-12-09  73.74
             Close  Prediction
Date                          
2019-11-26  118.66         NaN
2019-11-27  118.23         NaN
2019-11-29  118.56         NaN
2019-12-02  118.75         NaN
2019-12-03  118.14         NaN
[[ 74.95]
 [ 74.79]
 [ 74.23]
 ...
 [110.95]
 [111.17]
 [111.96]]
[ 70.79  70.34  69.14 ... 118.56 118.75 118.14]
lr confidence:  0.74221605032725

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  43.18  43.78  43.11  43.69  4255100      0.375             0
2014-12-04  43.60  43.97  43.41  43.77  3020900      0.000             0
2014-12-05  43.71  44.01  43.61  43.95  3070600      0.000             0
2014-12-08  43.92  43.92  43.56  43.72  3165500      0.000             0
2014-12-09  43.51  43.59  43.16  43.50  1676600      0.000             0
            Close
Date             
2014-12-03  43.69
2014-12-04  43.77
2014-12-05  43.95
2014-12-08  43.72
2014-12-09  43.50
             Close  Prediction
Date                          
2019-11-26  112.37         NaN
2019-11-27  112.43         NaN
2019-11-29  112.40         NaN
2019-12-02  111.14         NaN
2019-12-03  111.52         NaN
[[ 43.69]
 [ 43.77]
 [ 43.95]
 ...
 [114.78]
 [115.7 ]
 [117.46]]
[ 48.55  48.32  47.33 ... 112.4  111.14 111.52]
lr confidence:  0.93433130299616

             Open   High    Low  Close  Volume  Dividends  Stock Splits
Date                                                                   
2014-12-03  74.69  77.81  74.09  77.47  632200          0             0
2014-12-04  77.15  77.15  75.72  76.03  369100          0             0
2014-12-05  76.02  77.66  76.02  76.58  431900          0             0
2014-12-08  76.25  76.95  75.48  75.95  492300          0             0
2014-12-09  74.76  76.69  74.52  76.63  322500          0             0
            Close
Date             
2014-12-03  77.47
2014-12-04  76.03
2014-12-05  76.58
2014-12-08  75.95
2014-12-09  76.63
             Close  Prediction
Date                          
2019-11-26  321.04         NaN
2019-11-27  321.94         NaN
2019-11-29  322.07         NaN
2019-12-02  321.39         NaN
2019-12-03  320.96         NaN
[[ 77.47]
 [ 76.03]
 [ 76.58]
 ...
 [291.65]
 [286.08]
 [290.6 ]]
[ 84.52  85.11  82.59 ... 322.07 321.39 320.96]
lr confidence:  0.8789127520548825
[[29

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  86.37  86.73  85.66  86.53  1080000        0.0             0
2014-12-04  86.44  87.43  86.34  87.01  1458300        0.0             0
2014-12-05  87.25  88.26  86.92  88.15  2150800        0.0             0
2014-12-08  87.71  88.78  87.37  88.13  1676100        0.0             0
2014-12-09  86.93  91.17  86.93  90.44  3598500        0.0             0
            Close
Date             
2014-12-03  86.53
2014-12-04  87.01
2014-12-05  88.15
2014-12-08  88.13
2014-12-09  90.44
            Close  Prediction
Date                         
2019-11-26  48.71         NaN
2019-11-27  50.41         NaN
2019-11-29  50.33         NaN
2019-12-02  48.50         NaN
2019-12-03  47.71         NaN
[[86.53]
 [87.01]
 [88.15]
 ...
 [56.86]
 [56.47]
 [56.  ]]
[84.17 83.14 84.51 ... 50.33 48.5  47.71]
lr confidence:  0.38059835501153
[[55.3 ]
 [56.09]


             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  28.68  28.78  28.54  28.72  2227400        0.0             0
2014-12-04  28.66  28.67  28.42  28.62  2150500        0.0             0
2014-12-05  28.57  28.82  28.41  28.80  2673500        0.0             0
2014-12-08  28.82  29.32  28.80  29.27  3769100        0.0             0
2014-12-09  28.93  29.47  28.90  29.31  3630100        0.0             0
            Close
Date             
2014-12-03  28.72
2014-12-04  28.62
2014-12-05  28.80
2014-12-08  29.27
2014-12-09  29.31
            Close  Prediction
Date                         
2019-11-26  29.28         NaN
2019-11-27  29.41         NaN
2019-11-29  29.17         NaN
2019-12-02  28.87         NaN
2019-12-03  28.99         NaN
[[28.72]
 [28.62]
 [28.8 ]
 ...
 [24.92]
 [24.47]
 [25.58]]
[26.17 26.28 25.79 ... 29.17 28.87 28.99]
lr confidence:  0.19389499558974266
[[25.22]
 [25.4

              Open    High     Low   Close  Volume  Dividends  Stock Splits
Date                                                                       
2014-12-03  103.50  105.07  102.73  105.07  194200        0.0           0.0
2014-12-04  105.07  105.73  104.73  105.70  144800        0.0           0.0
2014-12-05  105.92  106.40  105.29  106.21  159200        0.0           0.0
2014-12-08  106.16  107.25  105.58  106.98  151200        0.0           0.0
2014-12-09  105.22  106.47  104.44  106.35  207100        0.0           0.0
             Close
Date              
2014-12-03  105.07
2014-12-04  105.70
2014-12-05  106.21
2014-12-08  106.98
2014-12-09  106.35
             Close  Prediction
Date                          
2019-11-26  194.82         NaN
2019-11-27  196.35         NaN
2019-11-29  196.44         NaN
2019-12-02  195.22         NaN
2019-12-03  192.52         NaN
[[105.07]
 [105.7 ]
 [106.21]
 ...
 [196.53]
 [196.  ]
 [198.53]]
[121.35 120.69 119.71 ... 196.44 195.22 192.52]
lr c

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  32.74  33.64  32.72  33.61  4057200        0.0           0.0
2014-12-04  33.35  33.71  33.24  33.59  2621700        0.0           0.0
2014-12-05  33.57  33.88  33.47  33.88  1678600        0.0           0.0
2014-12-08  33.97  33.97  33.19  33.26  2282700        0.0           0.0
2014-12-09  32.88  33.12  32.64  33.05  3098500        0.0           0.0
            Close
Date             
2014-12-03  33.61
2014-12-04  33.59
2014-12-05  33.88
2014-12-08  33.26
2014-12-09  33.05
            Close  Prediction
Date                         
2019-11-26  38.30         NaN
2019-11-27  38.80         NaN
2019-11-29  38.93         NaN
2019-12-02  38.50         NaN
2019-12-03  38.25         NaN
[[33.61]
 [33.59]
 [33.88]
 ...
 [34.8 ]
 [34.26]
 [34.15]]
[31.13 30.68 30.61 ... 38.93 38.5  38.25]
lr confidence:  0.155831570758716
[[33.66]
 [32.51]

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  50.36  50.39  49.37  49.79  4193800        0.0           0.0
2014-12-04  49.70  50.17  49.31  49.85  3092600        0.0           0.0
2014-12-05  50.08  50.36  49.84  50.22  2554400        0.0           0.0
2014-12-08  49.47  49.80  48.87  49.04  4730600        0.0           0.0
2014-12-09  48.49  48.72  48.10  48.24  6214000        0.0           0.0
            Close
Date             
2014-12-03  49.79
2014-12-04  49.85
2014-12-05  50.22
2014-12-08  49.04
2014-12-09  48.24
             Close  Prediction
Date                          
2019-11-26   99.75         NaN
2019-11-27  100.64         NaN
2019-11-29  100.67         NaN
2019-12-02  100.56         NaN
2019-12-03   99.45         NaN
[[ 49.79]
 [ 49.85]
 [ 50.22]
 ...
 [111.77]
 [112.  ]
 [113.12]]
[ 51.83  51.76  51.93 ... 100.67 100.56  99.45]
lr confidence:  0.87894520905422

             Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2014-12-03  43.20  43.46  42.86  43.33  2003600        0.0             0
2014-12-04  43.25  43.35  42.34  42.48  4294300        0.0             0
2014-12-05  42.45  42.93  42.32  42.46  3314000        0.0             0
2014-12-08  42.68  42.86  42.36  42.58  5889300        0.0             0
2014-12-09  41.69  42.96  41.27  42.31  5515000        0.0             0
            Close
Date             
2014-12-03  43.33
2014-12-04  42.48
2014-12-05  42.46
2014-12-08  42.58
2014-12-09  42.31
             Close  Prediction
Date                          
2019-11-26  121.89         NaN
2019-11-27  121.63         NaN
2019-11-29  120.52         NaN
2019-12-02  119.91         NaN
2019-12-03  120.53         NaN
[[ 43.33]
 [ 42.48]
 [ 42.46]
 ...
 [115.29]
 [114.5 ]
 [114.96]]
[ 45.55  45.68  45.32 ... 120.52 119.91 120.53]
lr confidence:  0.93572280307153